# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19O4GDL3qPBz2lrJfPRBQpDaThKPI5s2Z
"""

import numpy as np
import matplotlib.pyplot as plt
# Fungsi untuk menyelesaikan persamaan diferensial secara analitik
def penurunan_suhu(t, T0, Ta, k):
    """
    Menyelesaikan T(t) = Ta + e^-kt * T0

    Parameter:
    t : array-like, titik waktu
    T0 : float, suhu awal
    Ta : float, suhu ruangan
    k : float, konstanta laju pendinginan

    Mengembalikan:
    T : array-like, perubahan suhu pada setiap titik waktu
    """
    return Ta + np.exp(-k * t) * (T0 - Ta)

# Parameter contoh
T0 = 70  # suhu awal
Ta = 30  # suhu ruangan
k = 0.1  # konstanta laju pendinginan (10% per satuan waktu)
t = np.linspace(0, 50, 200)  # Titik waktu dari 0 hingga 50

# Menyelesaikan persamaan
T = penurunan_suhu(t, T0, Ta, k)

# Plot hasilnya
plt.figure(figsize=(8, 6))
plt.plot(t, T, label=f"T0 = {T0}C , Ta = {Ta}C , k = {k})", color="blue")
plt.title("Penurunan Suhu Seiring Waktu")
plt.xlabel("Waktu (t)")
plt.ylabel("Suhu (T)")
plt.legend()
plt.grid()
plt.show()