# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RY0WIqxhge0pUCXCXa510APc06ngA1tA
"""

import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk menghitung jumlah tanaman pada waktu tertentu t
def pertumbuhan_gandum(K, N0, r, t):
    return K / (1 + ((K - N0) / N0) * np.exp(-r * t))

# Parameter yang diberikan
N0 = 200  # jumlah tanaman awal
r = 0.2   # laju pertumbuhan
K = 20000 # kapasitas maksimum
t = np.arange(1, 13)  # waktu (bulan) dari 1 hingga 12

# Menghitung pertumbuhan tanaman untuk setiap bulan t
jumlah_gandum = pertumbuhan_gandum(K, N0, r, t)

# Plot hasilnya
plt.figure(figsize=(10, 6))
plt.plot(t, jumlah_gandum, marker='o', color='b', label='Jumlah Tanaman Gandum')
plt.title("Pertumbuhan Tanaman Gandum", fontsize=16)
plt.xlabel("Waktu (Bulan)", fontsize=12)
plt.ylabel("Jumlah Tanaman Gandum", fontsize=12)
plt.grid(True)
plt.xticks(t)
plt.legend()
plt.show()