# -*- coding: utf-8 -*-
"""Tugas 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_D_uMkSZy8N-sAQh2xEZP74sgkCSD7M
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def seir_model(y, t, a, v, beta, lambda1, lambda2, lambda3, mu, mu_i, alpha):
    S, E, I, R = y
    dSdt = a + v * R - (beta + lambda1 + mu) * S
    dEdt = beta * S - (alpha + lambda2 + mu) * E
    dIdt = lambda1 * S + lambda2 * E - (lambda3 + mu + mu_i) * I
    dRdt = alpha * E + lambda3 * I - (v + mu) * R
    return [dSdt, dEdt, dIdt, dRdt]

# Parameter berdasarkan jurnal
S0 = 36476   # Subpopulasi individu rentan
E0 = 3323    # Subpopulasi individu dalam masa inkubasi
I0 = 48      # Subpopulasi individu yang terinfeksi
R0 = 37      # Subpopulasi individu yang sembuh

# Parameter model
a = 0.021
v = 0.083
beta = 0.91
lambda1 = 0.0012
lambda2 = 0.00092
lambda3 = 0.00092
mu = 0.00012
mu_i = 0.125
alpha = 0.00092

# Waktu simulasi (dalam bulan, dikonversi ke hari)
t = np.linspace(0, 30 * 30, 900)

# Solusi numerik dari model SEIR
y0 = [S0, E0, I0, R0]
y = odeint(seir_model, y0, t, args=(a, v, beta, lambda1, lambda2, lambda3, mu, mu_i, alpha))
S, E, I, R = y.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, 'b', label='Rentan (S)')
plt.plot(t, E, 'y', label='Ekspos (E)')
plt.plot(t, I, 'r', label='Terinfeksi (I)')
plt.plot(t, R, 'g', label='Pulih (R)')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIR untuk Penyebaran Hepatitis')
plt.legend()
plt.grid()
plt.show()