# -*- coding: utf-8 -*-
"""Lokta Volterra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CprzI3tiBiPKahBPfimY8bVRW2yZJ38p
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter model
alpha = 0.5   # Laju pertumbuhan mangsa (rusa)
beta =0.02    # Tingkat perburuan oleh predator (serigala)
delta = 0.01  # Efisiensi konversi mangsa menjadi predator
gamma = 0.3   # Tingkat kematian alami predator

# Persamaan diferensial Lotka-Volterra
def lotka_voltera(y, t, alpha, beta, delta, gamma):
  x, y = y
  dxdt = alpha * x - beta * x * y # Perubahan populasi rusa
  dydt = delta * x * y - gamma * y # Perubahan populasi serigala
  return [dxdt, dydt]

# Kondisi awal: jumlah awal rusa dan serigala
y0 = [40, 9]

# Rentang waktu simulasi (0 sampai 200 unit waktu)
t = np.linspace(0, 200, 1000)

# Menyelesaikan persamaan diferensial
solution = odeint(lotka_voltera, y0, t, args=(alpha, beta, delta, gamma))
rusa, serigala = solution.T # Memisahkan hasil ke dua variabel

# Membuat grafik hasil simulasi
plt.figure(figsize=(10, 5))
plt.plot(t, rusa, label="Rusa (Prey)", color="blue", linewidth=2)
plt.plot(t, serigala, label="Serigala (Predator)", color="red", linewidth=2)
plt.xlabel("Waktu")
plt.ylabel("Populasi")
plt.title("Simulasi Model Lotka-Volterra Rusa vs Serigala")
plt.legend()
plt.grid()
plt.show()