# -*- coding: utf-8 -*-
"""matriks_eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19D_4ldHkEweHU78u6P-1jfnqEsgBkqq1
"""

import numpy as io

A = io.array([[4, 1], [2, 3]])
nilaieigen, vektoreigen = io.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)